# Generated by Django 2.0.7 on 2019-04-23 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatButton',
            fields=[
                ('hat_back_Id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='后扣 ID')),
                ('hat_back_button', models.CharField(max_length=50, verbose_name='后扣材质')),
                ('hat_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='后扣编号')),
                ('hat_back_image', models.ImageField(max_length=1000, upload_to='images/button', verbose_name='后扣图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '帽子后扣配置',
                'verbose_name_plural': '帽子后扣配置',
            },
        ),
    ]
