# Generated by Django 2.0.7 on 2019-04-23 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hatchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_status_one', models.CharField(blank=True, choices=[('1', '审核中'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(1)')),
                ('add_time_one', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(1)')),
                ('hat_status_two', models.CharField(blank=True, choices=[('1', '打样中'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(2)')),
                ('add_time_two', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(2)')),
                ('hat_status_three', models.CharField(blank=True, choices=[('1', '确认中'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(3)')),
                ('add_time_three', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(3)')),
                ('hat_status_four', models.CharField(blank=True, choices=[('1', '付定金'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(4)')),
                ('add_time_four', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(4)')),
                ('hat_status_five', models.CharField(blank=True, choices=[('1', '大货生产'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(5)')),
                ('add_time_five', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(5)')),
                ('hat_status_six', models.CharField(blank=True, choices=[('1', '运输中'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(6)')),
                ('add_time_six', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(6)')),
                ('hat_status_seven', models.CharField(blank=True, choices=[('1', '完成订单'), ('2', '')], max_length=20, null=True, verbose_name='流转状态(7)')),
                ('add_time_seven', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间(7)')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
                ('hat_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatchange.HatChange', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '订单流转',
                'verbose_name_plural': '订单流转',
            },
        ),
    ]
