# Generated by Django 2.0.7 on 2019-04-23 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatMessageReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_remark', models.TextField(blank=True, max_length=2000, null=True, verbose_name='需求备注')),
                ('hat_message_reply', models.TextField(blank=True, max_length=2000, null=True, verbose_name='留言回复')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='留言时间')),
                ('add_time2', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='回复时间')),
                ('hat_update_Id', models.IntegerField(blank=True, default=0, null=True, verbose_name='关联外键')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户名称')),
            ],
            options={
                'verbose_name': '留言交互',
                'verbose_name_plural': '留言交互',
            },
        ),
    ]
