# Generated by Django 2.0.7 on 2019-04-23 05:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hatmade', '0001_initial'),
        ('hatmaterials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HatChange',
            fields=[
                ('hat_update_Id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='定制产品ID')),
                ('hat_components_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='部件的颜色')),
                ('hat_components_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='部件的价格')),
                ('hat_change_color', models.CharField(blank=True, max_length=200, null=True, verbose_name='帽子的颜色')),
                ('hat_change_style', models.CharField(blank=True, max_length=500, null=True, verbose_name='款式')),
                ('hat_total_price', models.CharField(max_length=2000, verbose_name='总价')),
                ('hat_nums', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('hat_change_image1', models.CharField(max_length=2000, null=True, verbose_name='DIY后的成品图1')),
                ('hat_change_image2', models.CharField(max_length=2000, null=True, verbose_name='DIY后的成品图2')),
                ('hat_change_image3', models.CharField(max_length=2000, null=True, verbose_name='DIY后的成品图3')),
                ('hat_change_image4', models.CharField(max_length=2000, null=True, verbose_name='DIY后的成品图4')),
                ('hat_change_image5', models.CharField(max_length=2000, null=True, verbose_name='DIY后的成品图5')),
                ('hat_order_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='订单ID')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='下单时间')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
                ('hat_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmade.HatDiy', verbose_name='DIY后的样品')),
                ('hat_change_materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmaterials.HatMaterials', verbose_name='更换材质')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'DIY后的样品',
                'verbose_name_plural': 'DIY后的样品',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='upload_file/%Y/%m/%d/', verbose_name='文件')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
            ],
            options={
                'verbose_name': '客户上传文件',
                'verbose_name_plural': '客户上传文件',
            },
        ),
        migrations.CreateModel(
            name='UploadImageLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_logo/%Y/%m/%d/', verbose_name='logo')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
            ],
            options={
                'verbose_name': '客户上传logo',
                'verbose_name_plural': '客户上传logo',
            },
        ),
    ]
