# Generated by Django 2.0.7 on 2019-04-23 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatMaterials',
            fields=[
                ('hat_materials_Id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='材质 ID')),
                ('materials', models.CharField(blank=True, max_length=150, null=True, verbose_name='帽子材质')),
                ('materials_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='材质编号')),
                ('price', models.CharField(max_length=100, verbose_name='价格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '材质价格配置',
                'verbose_name_plural': '材质价格配置',
            },
        ),
    ]
