# Generated by Django 2.0.7 on 2019-04-23 05:27

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hatbutton', '0001_initial'),
        ('hatmaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner', verbose_name='主图')),
            ],
            options={
                'verbose_name': '首页分类',
                'verbose_name_plural': '首页分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '款式类别',
                'verbose_name_plural': '款式类别',
            },
        ),
        migrations.CreateModel(
            name='HatColorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='商品编号')),
                ('color', models.ImageField(max_length=1000, null=True, upload_to='hat_color_images/color', verbose_name='商品颜色')),
                ('image', models.ImageField(max_length=1000, upload_to='hat_color_images/front', verbose_name='商品原图')),
                ('hat_left', models.ImageField(max_length=1000, upload_to='hat_color_images/left', verbose_name='商品左侧图')),
                ('hat_right', models.ImageField(max_length=1000, upload_to='hat_color_images/right', verbose_name='商品右侧图')),
                ('hat_bottom', models.ImageField(blank=True, null=True, upload_to='hat_color_images/bottom', verbose_name='商品底部图')),
                ('hat_back', models.ImageField(blank=True, null=True, upload_to='hat_color_images/back', verbose_name='商品后背图')),
                ('hat_null_button', models.ImageField(blank=True, null=True, upload_to='hat_color_images/null_button', verbose_name='商品无后扣图')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
            ],
            options={
                'verbose_name': '商品多色图',
                'verbose_name_plural': '商品多色图',
            },
        ),
        migrations.CreateModel(
            name='HatColourName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_colour_number', models.IntegerField(blank=True, null=True, verbose_name='商品颜色编号')),
                ('hat_colour_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='商品颜色名称')),
            ],
            options={
                'verbose_name': '商品颜色',
                'verbose_name_plural': '商品颜色',
            },
        ),
        migrations.CreateModel(
            name='HatDiy',
            fields=[
                ('hat_made_Id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='商品 ID')),
                ('hat_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='商品编号')),
                ('hat_name', models.CharField(max_length=100, null=True, verbose_name='商品名称')),
                ('hat_brand', models.CharField(max_length=100, null=True, verbose_name='商品品牌')),
                ('image', models.ImageField(max_length=1000, null=True, upload_to='images/main', verbose_name='商品竖版图')),
                ('hat_right', models.ImageField(max_length=1000, null=True, upload_to='images/right', verbose_name='商品右侧侧图')),
                ('hat_left', models.ImageField(max_length=1000, null=True, upload_to='images/left', verbose_name='商品左侧图')),
                ('hat_bottom', models.ImageField(blank=True, null=True, upload_to='images/bottom', verbose_name='商品底部图')),
                ('hat_back', models.ImageField(blank=True, null=True, upload_to='images/back', verbose_name='商品后背图')),
                ('hat_null_button', models.ImageField(blank=True, null=True, upload_to='images/null_button', verbose_name='商品无后扣图')),
                ('hat_front', models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/front', verbose_name='商品正面图')),
                ('hat_price', models.CharField(max_length=500, verbose_name='价格')),
                ('hat_desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(default='', null=True, verbose_name='产品详情')),
                ('status', models.BooleanField(default=True, verbose_name='是否上线')),
                ('state', models.CharField(blank=True, default='点击进入', max_length=5, null=True, verbose_name='操作说明')),
                ('goods_categor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmade.GoodsCategor', verbose_name='所属系列')),
                ('goods_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmade.GoodsStyle', verbose_name='所属款式')),
                ('hat_change_materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmaterials.HatMaterials', verbose_name='默认材质')),
                ('hat_colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmade.HatColourName', verbose_name='商品颜色')),
                ('hatdiy_button', models.ManyToManyField(blank=True, to='hatbutton.HatButton', verbose_name='选择后扣')),
                ('hatdiy_color', models.ManyToManyField(blank=True, to='hatmade.HatColorImage', verbose_name='商品变色')),
            ],
            options={
                'verbose_name': '商品详情页',
                'verbose_name_plural': '商品详情页',
            },
        ),
        migrations.AddField(
            model_name='hatcolorimage',
            name='hat_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hatmade.HatColourName', verbose_name='商品颜色'),
        ),
        migrations.AddField(
            model_name='goodscategor',
            name='goods_name',
            field=models.ManyToManyField(blank=True, to='hatmade.GoodsName', verbose_name='所属商品分类'),
        ),
    ]
